import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { sparkManifest, type SparkType } from "../sparks/manifest";

const promptsDir = path.join(process.cwd(), "prompts");
const generatedPromptsFilePath = path.join(
  process.cwd(),
  "lib",
  "prompts",
  "generated.ts",
);
const generatedSparkSkillsFilePath = path.join(
  process.cwd(),
  "lib",
  "sparks",
  "skills",
  "generated.ts",
);

type PromptFile = {
  path: string;
  content: string;
};

type SparkSkillMetadata = {
  name: string;
  description: string;
  whenToUse: string;
  promptPath: string;
};

function normalizePromptText(text: string): string {
  return text.replace(/\r\n/g, "\n").trim();
}

function toPosixPath(input: string): string {
  return input.split(path.sep).join("/");
}

function parseFrontmatter(text: string): {
  content: string;
  frontmatter: Record<string, string>;
} {
  const normalized = normalizePromptText(text);
  if (!normalized.startsWith("---\n")) {
    return { content: normalized, frontmatter: {} };
  }

  const closingIndex = normalized.indexOf("\n---\n", 4);
  if (closingIndex === -1) {
    throw new Error(
      "Invalid frontmatter block. Missing closing delimiter (`---`).",
    );
  }

  const frontmatterBlock = normalized.slice(4, closingIndex).trim();
  const body = normalized.slice(closingIndex + 5).trim();
  const frontmatter: Record<string, string> = {};

  if (frontmatterBlock.length === 0) {
    return { content: body, frontmatter };
  }

  for (const line of frontmatterBlock.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }

    const separatorIndex = trimmed.indexOf(":");
    if (separatorIndex <= 0) {
      throw new Error(`Invalid frontmatter line: '${line}'`);
    }

    const key = trimmed.slice(0, separatorIndex).trim();
    let value = trimmed.slice(separatorIndex + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    frontmatter[key] = value;
  }

  return {
    content: body,
    frontmatter,
  };
}

async function collectPromptPaths(
  dirPath: string,
  rootPath: string,
): Promise<string[]> {
  const entries = await readdir(dirPath, { withFileTypes: true });
  const sorted = [...entries].sort((a, b) => a.name.localeCompare(b.name));
  const files: string[] = [];

  for (const entry of sorted) {
    const fullPath = path.join(dirPath, entry.name);

    if (entry.isDirectory()) {
      const nested = await collectPromptPaths(fullPath, rootPath);
      files.push(...nested);
      continue;
    }

    if (!entry.isFile() || path.extname(entry.name) !== ".md") {
      continue;
    }

    const relativePath = path.relative(rootPath, fullPath);
    files.push(toPosixPath(relativePath));
  }

  return files;
}

function buildPromptsGeneratedSource(
  promptMap: Record<string, string>,
): string {
  return [
    "// This file is auto-generated by `bun run prompts:sync`.",
    "// Do not edit this file directly. Edit files in `prompts/` instead.",
    "",
    "export const embeddedPrompts: Readonly<Record<string, string>> = Object.freeze(",
    `${JSON.stringify(promptMap, null, 2)}`,
    ");",
    "",
  ].join("\n");
}

function buildSparkSkillsGeneratedSource(
  metadataById: Record<SparkType, SparkSkillMetadata>,
): string {
  return [
    "// This file is auto-generated by `bun run prompts:sync`.",
    "// Do not edit this file directly. Edit `lib/sparks/manifest.ts` instead.",
    "",
    'import type { SparkType } from "../manifest";',
    "",
    "export type SparkSkillMetadata = {",
    "  name: string;",
    "  description: string;",
    "  whenToUse: string;",
    "  promptPath: string;",
    "};",
    "",
    "export const sparkSkillMetadataById: Readonly<Record<SparkType, SparkSkillMetadata>> = Object.freeze(",
    `${JSON.stringify(metadataById, null, 2)}`,
    ");",
    "",
  ].join("\n");
}

async function readFileIfExists(filePath: string): Promise<string> {
  try {
    return await readFile(filePath, "utf8");
  } catch {
    return "";
  }
}

async function buildArtifacts(): Promise<{
  promptsSource: string;
  sparkSkillsSource: string;
}> {
  const promptPaths = await collectPromptPaths(promptsDir, promptsDir);
  const promptFiles = await Promise.all(
    promptPaths.map(async (promptPath) => {
      const absolutePath = path.join(promptsDir, promptPath);
      const raw = await readFile(absolutePath, "utf8");
      const parsed = parseFrontmatter(raw);
      return {
        path: promptPath,
        content: parsed.content,
      } satisfies PromptFile;
    }),
  );

  const promptMap = Object.fromEntries(
    promptFiles.map((file) => [file.path, file.content]),
  ) as Record<string, string>;

  const promptFileByPath = new Map(
    promptFiles.map((file) => [file.path, file] as const),
  );

  const sparkSkillMetadataEntries = sparkManifest.map((spark) => {
    const promptPath = spark.promptPath;
    const promptFile = promptFileByPath.get(promptPath);
    if (!promptFile) {
      throw new Error(
        `Missing prompt file for spark '${spark.id}'. Expected prompts/${promptPath}.`,
      );
    }

    return [
      spark.id,
      {
        name: spark.label,
        description: spark.description,
        whenToUse: spark.whenToUse,
        promptPath,
      },
    ] as const;
  });

  const sparkSkillMetadataById = Object.fromEntries(
    sparkSkillMetadataEntries,
  ) as Record<SparkType, SparkSkillMetadata>;

  return {
    promptsSource: buildPromptsGeneratedSource(promptMap),
    sparkSkillsSource: buildSparkSkillsGeneratedSource(sparkSkillMetadataById),
  };
}

async function main(): Promise<void> {
  const checkOnly = process.argv.includes("--check");
  const artifacts = await buildArtifacts();

  const [currentPromptsSource, currentSparkSkillsSource] = await Promise.all([
    readFileIfExists(generatedPromptsFilePath),
    readFileIfExists(generatedSparkSkillsFilePath),
  ]);

  const promptsUpToDate = currentPromptsSource === artifacts.promptsSource;
  const sparkSkillsUpToDate =
    currentSparkSkillsSource === artifacts.sparkSkillsSource;
  const isUpToDate = promptsUpToDate && sparkSkillsUpToDate;

  if (checkOnly) {
    if (!isUpToDate) {
      console.error(
        "Prompt artifacts are out of date. Run `bun run prompts:sync` and commit the result.",
      );
      process.exit(1);
    }
    console.log("Prompt artifacts are up to date.");
    return;
  }

  if (isUpToDate) {
    console.log("Prompt artifacts are already up to date.");
    return;
  }

  await Promise.all([
    mkdir(path.dirname(generatedPromptsFilePath), { recursive: true }),
    mkdir(path.dirname(generatedSparkSkillsFilePath), { recursive: true }),
  ]);

  await Promise.all([
    writeFile(generatedPromptsFilePath, artifacts.promptsSource, "utf8"),
    writeFile(
      generatedSparkSkillsFilePath,
      artifacts.sparkSkillsSource,
      "utf8",
    ),
  ]);

  console.log(
    `Updated ${path.relative(process.cwd(), generatedPromptsFilePath)}.`,
  );
  console.log(
    `Updated ${path.relative(process.cwd(), generatedSparkSkillsFilePath)}.`,
  );
}

main().catch((error) => {
  console.error(`Failed to sync prompts: ${String(error)}`);
  process.exit(1);
});
