// This file is auto-generated by `bun run prompts:sync`.
// Do not edit this file directly. Edit files in `prompts/sparks/skills/*.md` frontmatter instead.

import type { SparkType } from "../contracts";

export type SparkSkillMetadata = {
  name: string;
  description: string;
  whenToUse: string;
  promptPath: string;
};

export const sparkSkillMetadataById: Readonly<Record<SparkType, SparkSkillMetadata>> = Object.freeze(
{
  "scene": {
    "name": "Spark Scene",
    "description": "Create a single self-contained HTML file for a micro-interactive learning visualization.",
    "whenToUse": "Use when the learner would understand better with an interactive visual demo instead of text alone.",
    "promptPath": "sparks/skills/scene.md"
  },
  "quiz": {
    "name": "Quiz",
    "description": "Create a structured quiz artifact with multiple questions, instant feedback, and scoring.",
    "whenToUse": "Use when the learner should check understanding with short questions and immediate correctness feedback.",
    "promptPath": "sparks/skills/quiz.md"
  },
  "flash_card": {
    "name": "Flash Card",
    "description": "Create a structured flash-card artifact for active recall and quick self-testing.",
    "whenToUse": "Use when the learner should memorize definitions, terms, formulas, or paired concepts through repeated recall.",
    "promptPath": "sparks/skills/flash-card.md"
  },
  "desmos_graph": {
    "name": "Desmos Graph",
    "description": "Create an interactive Desmos graph with equations, points, and data tables for math exploration.",
    "whenToUse": "Use when the learner needs to visualize equations, compare multiple functions, inspect points, or manipulate table-driven data.",
    "promptPath": "sparks/skills/desmos-graph.md"
  },
  "code_playground": {
    "name": "Code Playground",
    "description": "Create an editable coding spark with starter code and a short challenge.",
    "whenToUse": "Use when the learner should practice by editing and running code to verify understanding.",
    "promptPath": "sparks/skills/code-playground.md"
  },
  "web_playground": {
    "name": "Web Playground",
    "description": "Create an editable HTML/CSS/JS playground spark with live preview for frontend practice.",
    "whenToUse": "Use when the learner should practice web fundamentals by editing HTML, CSS, and JavaScript and seeing immediate visual output.",
    "promptPath": "sparks/skills/web-playground.md"
  }
}
);
